export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const GET_MOVIE_SEARCH = 'GET_MOVIE_SEARCH';
